// cCKF/tests/test_chi2_logodds.cpp
//
// Standalone parity test (no ACTS dependency) for cckf::chi2LogOdds in
// acts_patches/cckf/CckfFeatures.hpp against the Python reference
// cckf.features.chi2_log_odds — the quantity build_value_cache.py
// accumulates into sum_gate_logodds / min_gate_logodds for the value
// function's training cache. CckfBranchStopperWrapper must produce the
// same numbers at inference, so a drift here is a train/inference skew on
// two standardized value-net features.
//
// Reads tests/fixtures/chi2_logodds_ref.bin: (n, 2) float64 rows of
// (chi2, expected_log_odds), regenerated by
// tests/test_features.py::test_chi2_log_odds_cpp_fixture_roundtrip.
//
// Build (from cCKF/):
//   clang++ -std=c++17 -O2 -Iacts_patches/cckf tests/test_chi2_logodds.cpp \
//       -o /tmp/test_chi2_logodds
// Run:
//   /tmp/test_chi2_logodds [path/to/tests/fixtures]

#include "CckfFeatures.hpp"

#include <cmath>
#include <cstdio>
#include <fstream>
#include <limits>
#include <string>
#include <vector>

int main(int argc, char** argv) {
  const std::string fixtures_dir = (argc > 1) ? argv[1] : "tests/fixtures";
  const std::string path = fixtures_dir + "/chi2_logodds_ref.bin";

  std::ifstream f(path, std::ios::binary);
  if (!f) {
    std::fprintf(stderr, "FAIL: cannot open fixture %s\n", path.c_str());
    std::fprintf(stderr,
                 "Regenerate with: pytest tests/test_features.py::"
                 "test_chi2_log_odds_cpp_fixture_roundtrip\n");
    return 1;
  }
  f.seekg(0, std::ios::end);
  const auto nbytes = static_cast<std::size_t>(f.tellg());
  f.seekg(0, std::ios::beg);
  if (nbytes == 0 || nbytes % (2 * sizeof(double)) != 0) {
    std::fprintf(stderr, "FAIL: fixture has %zu bytes, not a multiple of 16\n",
                 nbytes);
    return 1;
  }
  const std::size_t n = nbytes / (2 * sizeof(double));
  std::vector<double> rows(2 * n);
  f.read(reinterpret_cast<char*>(rows.data()),
         static_cast<std::streamsize>(nbytes));
  if (!f) {
    std::fprintf(stderr, "FAIL: truncated fixture read\n");
    return 1;
  }

  int failures = 0;

  // --- Test 1: parity with the Python reference on every fixture row ---
  // chi2LogOdds computes in double and casts the result to float, so the
  // only expected discrepancy is float32 rounding of a value bounded by
  // |log(1e-6/(1-1e-6))| < 14; 1e-4 absolute is generous.
  constexpr float kTol = 1e-4f;
  for (std::size_t i = 0; i < n; ++i) {
    const auto chi2 = static_cast<float>(rows[2 * i]);
    const auto expected = static_cast<float>(rows[2 * i + 1]);
    const float got = cckf::chi2LogOdds(chi2);
    if (!(std::abs(got - expected) <= kTol)) {
      std::fprintf(stderr,
                   "FAIL: chi2LogOdds(%g) = %.7g, python reference %.7g\n",
                   static_cast<double>(chi2), static_cast<double>(got),
                   static_cast<double>(expected));
      ++failures;
    }
  }

  // --- Test 2: edge-case conventions ---
  // Negative chi2 clamps to 0 (same output as chi2 = 0).
  if (cckf::chi2LogOdds(-1.0f) != cckf::chi2LogOdds(0.0f)) {
    std::fprintf(stderr, "FAIL: negative chi2 not clamped to 0\n");
    ++failures;
  }
  // Non-finite chi2 maps to the most-negative clipped value,
  // log(1e-6 / (1 - 1e-6)).
  const float floorVal =
      static_cast<float>(std::log(1e-6 / (1.0 - 1e-6)));
  const float nanVal = cckf::chi2LogOdds(std::nanf(""));
  const float infVal =
      cckf::chi2LogOdds(std::numeric_limits<float>::infinity());
  if (nanVal != floorVal || infVal != floorVal) {
    std::fprintf(stderr, "FAIL: non-finite chi2 -> %g / %g, want %g\n",
                 static_cast<double>(nanVal), static_cast<double>(infVal),
                 static_cast<double>(floorVal));
    ++failures;
  }
  // Output is always finite.
  if (!std::isfinite(cckf::chi2LogOdds(0.0f)) ||
      !std::isfinite(cckf::chi2LogOdds(1e30f))) {
    std::fprintf(stderr, "FAIL: non-finite output at a saturation end\n");
    ++failures;
  }

  if (failures == 0) {
    std::printf("PASS: %zu fixture rows + edge cases\n", n);
    return 0;
  }
  std::fprintf(stderr, "%d failure(s)\n", failures);
  return 1;
}
