"""The V^{π†} value target (spec §3.3).

Definition
----------
V^{π†} is the DM-match quality a branch would reach if a truth-greedy oracle
took over at step k and picked correctly from there on::

    n_shared_final = n_correct + n_findable
    n_track_final  = n_correct + n_wrong + n_findable
    completeness   = n_shared_final / N_total_true
    purity         = n_shared_final / n_track_final
    V^{π†}         = min(completeness, purity)

The ``min`` is the whole point. Double-majority matching requires **both**
purity ≥ 0.5 and completeness ≥ 0.5, so a branch fails if either fails, and the
value of a state is governed by whichever constraint is closer to binding. A
branch that has collected 20 hits of which 12 are wrong has fine completeness
and hopeless purity; one that has 5 perfect hits on a 20-hit particle has
perfect purity and hopeless completeness. A single ratio cannot express both.

The target is left **soft** in [0, 1] rather than thresholded at 0.5. V = 0.45
means "nearly matchable"; V = 0.05 means "hopeless". Hard labels would collapse
that distinction and destroy the gradient that teaches the network *how far*
from viable a branch is.

Where the numbers come from
---------------------------
Backward part (steps 0..k, already determined — a fact about what happened):
    ``n_correct`` and ``n_wrong`` count the CKF-**selected** hits so far,
    split by whether the branch's majority particle contributed to that
    cluster. This is why ``is_ckf_selected`` (see ``scripts/patch_is_selected``)
    is a prerequisite: the expanded Parquet holds every in-window candidate,
    not just the accepted one, so without that flag "the hits accepted so far"
    is not recoverable.

Forward part (steps > k, the oracle's contribution):
    ``n_findable`` counts surfaces the branch will visit where the majority
    particle actually left a simhit — read off the precomputed
    ``majority_true_hit_on_surface`` column, which the expansion already
    evaluated per (branch, surface) against ``simhits.csv``.

``N_total_true`` is the total number of simhits the majority particle deposited
anywhere in the detector, from ``simhits.csv`` grouped by ``particle_id``.

The three tiers
---------------
Tier 1 — ``vstar_t1`` (V*_truth, most optimistic)
    Counts *all* of the particle's remaining simhits beyond step k, whether or
    not the branch's trajectory ever reaches those surfaces.

Tier 2 — ``vstar_t2`` (**the training target**)
    Counts only the particle's simhits on surfaces the branch actually
    propagated through. This excludes surfaces the trajectory never reaches
    (e.g. the particle curls into a different volume), which Tier 1 would
    credit the branch for finding.

Tier 3 — window-restricted. **Not computed here. Requires a CKF rollout.**
    Tier 3 additionally demands that the majority particle's hit fall inside the
    n-σ window at the predicted position *under the truth-greedy rollout*. That
    cannot be read off this Parquet, and the tempting shortcut is wrong.

    The shortcut: candidate rows exist only for in-window measurements
    (``expansion.py:753``), so it looks as though "any candidate at step j with
    branch_majority_pid ∈ contrib_pids" is the window-restricted oracle. It is
    not. Those windows were generated by the **behaviour** policy's trajectory —
    the window at step j is set by the predicted state at j, which is set by
    which hits were accepted at steps 0..j−1. Tier 3 is defined under π†, whose
    predicted states diverge from the log the moment the logged branch accepted a
    wrong hit. So for any branch that went wrong at step k the shortcut reads
    windows from a corrupted trajectory — and those are exactly the branches
    whose value is interesting. The error is anti-correlated with the target's
    purpose, which is worse than a uniform bias.

    Why the same logged-trajectory substitution is fine for Tier 2 and fatal for
    Tier 3: **a surface sequence is robust to policy perturbation; window
    membership is not.** Which layers a branch crosses is largely fixed by its
    momentum, so accepting a slightly wrong hit usually leaves the sequence
    intact — which is why spec §3.3 defines Tier 2 against the propagation
    recorded in the Parquet. A window is ±n·√S, tight and state-sensitive; a
    single wrong hit can displace the predicted position by more than the window
    width, flipping membership outright.

    Computing Tier 3 honestly therefore means re-running propagation with
    truth-greedy selection to regenerate the windows. That is CKF deployment
    work, deferred with §5. Note this has nothing to do with
    ``truth_residual_l0/l1`` being NaN — even fully populated, they would
    describe the logged trajectory's residuals, not π†'s.

Known limitation: surface revisits can invert the tiers
---------------------------------------------------------
``maj_hit_on_surface`` is evaluated per **state** (one row per branch step), not
per distinct surface. If a branch revisits the same surface — a low-momentum or
looping trajectory re-crossing a layer — and the majority particle has a hit
there, that one real simhit is counted once per visit instead of once per
surface. ``n_findable_t1``'s ``n_total - cum_maj`` and ``n_findable_t2``'s
forward sum both inherit this over-count, which inflates both completeness and
purity — the target is biased **optimistically**, and for exactly the marginal,
looping branches whose value is most consequential to get right.

The over-count is asymmetric between tiers, because Tier 1 clamps the running
total at 0 (``np.maximum(n_total - cum_maj, 0.0)``) while Tier 2's forward count
does not renormalize against ``n_total`` at all. On a branch that revisits a
surface enough times, this can push ``vstar_t2`` strictly above ``vstar_t1``,
inverting the documented ``vstar_t1 >= vstar_t2`` invariant outright — not just
eroding the margin.

This module does not fix the root cause. The principled fix is to dedupe
``maj_hit_on_surface`` to first-visit-per-surface using a ``surface_id`` column,
so a revisited surface contributes at most once to either tier's forward count.
That fix is deferred: it requires threading ``surface_id`` through
:func:`build_step_table` and changing this function's input contract, which is
out of scope here.

Instead, :func:`compute_value_targets` adds a boolean column,
``tier_invariant_violated``, set when ``vstar_t1 < vstar_t2 - 1e-12`` (with both
values known/non-NaN). This flag catches only the **severe** cases — those bad
enough to flip the ordering of the two tiers. It does not catch the milder,
far more common case where revisits inflate both tiers together without
inverting them; those rows pass through unflagged with a target that is still
biased high, just not detectably so from the tier comparison alone. Consumers
of ``vstar_t2`` as a training target are expected to drop rows where
``tier_invariant_violated`` is True, the same way they are expected to drop
rows with a NaN target.

The Tier 1 − Tier 2 gap
-----------------------
Both tiers are computed together, so the gap is free. It is a difference between
**target definitions** on truth; the trained network is not involved. There is
one V_φ and it is trained on Tier 2 — "Tier 1 vs Tier 2" is not two value
functions being compared.

It is also not a convergence criterion. §5.4's stopping rule is "validation AUC
and ECE plateau across two consecutive iterations"; the gap sits alongside it as
a *stability* monitor. Since the sole difference between the definitions is which
surfaces count, the gap moves only when the visited-surface distribution moves —
so a stable gap is evidence that the state distribution has settled, not that the
model has converged. At iteration 0 it is a single scalar with nothing to compare
against; it becomes a diagnostic only once successive iterations exist (deferred
with §5).
"""

from __future__ import annotations

from typing import Mapping

import numpy as np
import pandas as pd

_GROUP = ["seed_id", "branch_id"]


def particle_simhit_counts(simhits: pd.DataFrame) -> dict[int, int]:
    """Total simhits per particle: ``N_total_true``.

    Parameters
    ----------
    simhits : pandas.DataFrame
        Output of ``expansion.load_simhits``; needs a ``particle_id`` column.

    Returns
    -------
    dict of int to int
        particle_id → number of simhits anywhere in the detector.
    """
    counts = simhits.groupby("particle_id").size()
    return {int(k): int(v) for k, v in counts.items()}


def build_step_table(df: pd.DataFrame) -> pd.DataFrame:
    """Collapse candidate rows to one row per ``(seed_id, branch_id, step_k)``.

    The value function acts on branch *states*, not candidates, so the per-
    candidate Parquet must be reduced first (spec §3.5: one row per
    (branch, surface) pair).

    Parameters
    ----------
    df : pandas.DataFrame
        Candidate rows with ``seed_id``, ``branch_id``, ``step_k``,
        ``cand_hit_id``, ``is_ckf_selected``, ``label_same_particle``,
        ``majority_true_hit_on_surface``, ``branch_majority_pid``.

    Returns
    -------
    pandas.DataFrame
        One row per state, with ``sel_correct`` / ``sel_wrong`` (0/1) describing
        the accepted hit, ``maj_hit_on_surface`` (the Tier 2 oracle), and
        ``branch_majority_pid``.
        A hole step has ``sel_correct == sel_wrong == 0``: it neither helps nor
        pollutes the track, it only costs completeness.
    """
    work = df.copy()
    sel = work["is_ckf_selected"].to_numpy(dtype=bool)
    is_hit = work["cand_hit_id"].to_numpy(dtype=np.int64) != -1
    correct = work["label_same_particle"].to_numpy(dtype=np.int64) == 1

    work["sel_correct"] = ((sel & is_hit & correct)).astype(np.int64)
    work["sel_wrong"] = ((sel & is_hit & ~correct)).astype(np.int64)
    work["maj_hit_on_surface"] = work["majority_true_hit_on_surface"].astype(bool)

    grouped = work.groupby([*_GROUP, "step_k"], as_index=False).agg(
        sel_correct=("sel_correct", "max"),
        sel_wrong=("sel_wrong", "max"),
        maj_hit_on_surface=("maj_hit_on_surface", "max"),
        branch_majority_pid=("branch_majority_pid", "first"),
    )
    return grouped.sort_values([*_GROUP, "step_k"]).reset_index(drop=True)


def compute_value_targets(
    step: pd.DataFrame, particle_nhits: Mapping[int, int]
) -> pd.DataFrame:
    """Compute Tier-1 and Tier-2 V^{π†} for every branch state.

    Parameters
    ----------
    step : pandas.DataFrame
        Output of :func:`build_step_table`, or any frame with ``seed_id``,
        ``branch_id``, ``step_k``, ``sel_correct``, ``sel_wrong``,
        ``maj_hit_on_surface``, ``branch_majority_pid``.
    particle_nhits : mapping of int to int
        ``N_total_true`` per particle, from :func:`particle_simhit_counts`.

    Returns
    -------
    pandas.DataFrame
        ``step`` plus ``n_correct``, ``n_wrong``, ``n_findable_t1``,
        ``n_findable_t2``, ``completeness``, ``purity`` (both for Tier 2, the
        training target), ``vstar_t1`` and ``vstar_t2``. Rows whose majority
        particle is absent from ``particle_nhits`` get NaN targets and must be
        dropped before training — a missing count is unknown, not zero.

        Also adds ``tier_invariant_violated`` (bool): True where ``vstar_t1 <
        vstar_t2 - 1e-12``, i.e. where a surface revisit has over-counted
        ``maj_hit_on_surface`` badly enough to invert the two tiers. See the
        module docstring's "Known limitation" section — this flags only the
        severe, invariant-breaking cases, not every row a revisit has biased.
        Never True when either ``vstar_t1`` or ``vstar_t2`` is NaN. Consumers
        should drop flagged rows before training, same as NaN rows.

        In general (i.e. outside the flagged rows) ``vstar_t1 >= vstar_t2``.
    """
    out = step.sort_values([*_GROUP, "step_k"]).reset_index(drop=True).copy()
    grp = out.groupby(_GROUP, sort=False)
    keys = [out["seed_id"], out["branch_id"]]

    # Backward: inclusive of step k, since those hits are already on the branch.
    out["n_correct"] = grp["sel_correct"].cumsum().to_numpy()
    out["n_wrong"] = grp["sel_wrong"].cumsum().to_numpy()

    def _forward(col: str) -> np.ndarray:
        """Count of `col`-flagged steps strictly after k, per branch."""
        flag = out[col].astype(np.int64)
        total = flag.groupby(keys).transform("sum")
        cumulative = flag.groupby(keys).cumsum()
        return (total - cumulative).to_numpy()

    # Tier 2: surfaces after k where the majority particle left any simhit.
    out["n_findable_t2"] = _forward("maj_hit_on_surface")

    n_total = (
        out["branch_majority_pid"]
        .map(particle_nhits)
        .astype("Float64")
        .to_numpy(dtype=np.float64)
    )

    # Tier 1: every remaining simhit of the particle, whether or not the branch's
    # trajectory reaches that surface. Clamped at 0 because a branch can revisit
    # surfaces, which would otherwise push the remainder negative.
    cum_maj = (
        out["maj_hit_on_surface"].astype(np.int64).groupby(keys).cumsum().to_numpy()
    )
    out["n_findable_t1"] = np.maximum(n_total - cum_maj, 0.0)

    def _finish(n_findable: np.ndarray, suffix: str) -> None:
        n_shared = out["n_correct"].to_numpy() + n_findable
        n_track = out["n_correct"].to_numpy() + out["n_wrong"].to_numpy() + n_findable
        with np.errstate(divide="ignore", invalid="ignore"):
            completeness = np.where(n_total > 0, n_shared / n_total, np.nan)
            purity = np.where(n_track > 0, n_shared / n_track, 0.0)
        # A branch cannot find more of the particle than the particle deposited.
        completeness = np.clip(completeness, 0.0, 1.0)
        purity = np.clip(purity, 0.0, 1.0)
        if suffix == "_t2":  # the training target keeps its components exposed
            out["completeness"] = completeness
            out["purity"] = purity
        out[f"vstar{suffix}"] = np.minimum(completeness, purity)

    for suffix in ("_t1", "_t2"):
        _finish(out[f"n_findable{suffix}"].to_numpy(dtype=np.float64), suffix)

    # Accepted limitation (see module docstring, "Known limitation" section):
    # `maj_hit_on_surface` over-counts on a revisited surface, which can inflate
    # n_findable_t2 past n_findable_t1 and invert the two tiers. Flag rather than
    # silently correct. Explicit NaN handling below, even though a NaN compares
    # False under `<` in numpy/pandas anyway — the intent (never flag an
    # already-unknown target as a "violation") should not depend on that
    # incidental fact.
    v1 = out["vstar_t1"].to_numpy(dtype=np.float64)
    v2 = out["vstar_t2"].to_numpy(dtype=np.float64)
    both_known = ~np.isnan(v1) & ~np.isnan(v2)
    out["tier_invariant_violated"] = both_known & (v1 < v2 - 1e-12)

    return out
